---
ID: "a12c373f-ceae-5465-8fb5-7ed6d684516c"
Parent: "40238910-9a62-5e84-b60b-b2d9478aa6b6"
Template: "40238910-9a62-5e84-b60b-b2d9478aa6b6"
Path: "/sitecore/templates/Project/scnextjs/Styleguide-SitecoreContext/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220811T000911Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4f9d4b0a-181b-4173-b2e9-6996359c86de"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220811T000911Z
