---
ID: "ee7a4f7e-d5e8-5ea0-b954-f1377eb35db4"
Parent: "2dbfdafa-5799-5d40-8b9a-2d68df7b227c"
Template: "2dbfdafa-5799-5d40-8b9a-2d68df7b227c"
Path: "/sitecore/templates/Project/scnextjs/Styleguide-RouteFields/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220811T000910Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6cc8e504-b490-45e7-8e69-74c4e97e78bb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220811T000910Z
