---
ID: "e490a291-97ec-566d-996b-aaf6e43cbfd3"
Parent: "b00bcf62-cff9-5102-a725-e814abbf5a4d"
Template: "b00bcf62-cff9-5102-a725-e814abbf5a4d"
Path: "/sitecore/templates/Project/scnextjs/Styleguide-FieldUsage-Date/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220811T000856Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c2faa657-8dec-42e7-b412-3fdb96b85ca3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220811T000856Z
